package org.gokapp.proxy.server.omg;


/**
* org/gokapp/proxy/server/omg/ProxyServerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ProxyServer.idl
* Friday, May 15, 2015 10:26:07 AM EDT
*/

public interface ProxyServerOperations 
{
  void startup ();
} // interface ProxyServerOperations
